acmebscene_meetup:
    resource: "@AcmebsceneBundle/Resources/config/routing/meetup.yml"
    prefix:   /meetup

acmebscene_eventComments:
    resource: "@AcmebsceneBundle/Resources/config/routing/eventcomments.yml"
    prefix:   /eventComments

acmebscene_speaker:
    resource: "@AcmebsceneBundle/Resources/config/routing/speaker.yml"
    prefix:   /speaker

acmebscene_meeting:
    resource: "@AcmebsceneBundle/Resources/config/routing/meeting.yml"
    prefix:   /meeting

acmebscene_organization:
    resource: "@AcmebsceneBundle/Resources/config/routing/organization.yml"
    prefix:   /organization

acmebscene_category:
    resource: "@AcmebsceneBundle/Resources/config/routing/categories.yml"
    prefix:   /category

acmebscene_account:
    resource: "@AcmebsceneBundle/Resources/config/routing/account.yml"
    prefix:   /account

acmebscene_homepage:
    path:     ''
    defaults: { _controller: AcmebsceneBundle:Default:index }
    
acmebscene_admin:
    path:     /admin
    defaults: { _controller: AcmebsceneBundle:Default:login }

acmebscene_dashboard:
    path:   /admin/{lastLogin}
    defaults: { _controller: AcmebsceneBundle:Admin:index }
    
acmebscene_calender:
     path: /calender
     defaults: { _controller: AcmebsceneBundle:Default:getEventsDayList,_format: json  }
     
 
acmebscene_adminComment:
    path:   /admin/comment/{lastLogin}
    defaults: { _controller: AcmebsceneBundle:Comment:adminIndex}


meeting_admin_list:
    path:    /admin/newEvents/{lastLogin}
    defaults: { _controller: "AcmebsceneBundle:Admin:newMeetingList" }    
 
acmebscene_homepageCalender:
    path:     /calender
    defaults: { _controller: AcmebsceneBundle:Default:getEventsDayList }
    
acmebscene_eventDetail:
    path: /meeting/detail/{id}
    defaults: {_controller: AcmebsceneBundle:Meeting:show }
        
acmebscene_logout:
    path:   /logout
    defaults: { _controller: AcmebsceneBundle:Default:logout }
    
    
acmebscene_login:
    path:   /login
    defaults: { _controller: AcmebsceneBundle:Default:login }

acmebscene_keywordSearch:
    path: /meeting/searchResults/
    defaults: {_controller: AcmebsceneBundle:Meeting:keywordSearch }
    
acmebscene_categorySearch:
    path: /meeting/searchResults/{id}
    defaults: {_controller: AcmebsceneBundle:Meeting:categorySearch }
    
    
acmebscene_dateSearch:
    path: /meeting/eventByDay/{day}
    defaults: {_controller: AcmebsceneBundle:Meeting:dateSearch }
    
acmebscene_contact:
    path: /default/contact/
    defaults: {_controller: AcmebsceneBundle:Default:contact }
    
acmebscene_about:
    path: /default/about/
    defaults: {_controller: AcmebsceneBundle:Default:about }
    
acmebscene_newAccount:
    path: /account/new/
    defaults: {_controller: AcmebsceneBundle:Account:create }
    
acmebscene_subscribe:
    path: /account/subscribe/
    defaults: {_controller: AcmebsceneBundle:Account:subscribe }
 

acmebscene_newSubscribe:
    path: /account/newSubscription/
    defaults: {_controller: AcmebsceneBundle:Account:newSubscription }
    
acmebscene_accountDetail:
    path: /account/detail/{id}
    defaults: {_controller: AcmebsceneBundle:Account:show }
    
acmebscene_emailValidated:
    path: /account/validated/{id}/{hash}
    defaults: {_controller: AcmebsceneBundle:Account:emailValidated }
    
acmebscene_saveSubscription:
    path: /account/newsubscription/
    defaults: {_controller: AcmebsceneBundle:Account:newSubscription }

acmebscene_addComment:
    path: /meeting/addComment/{id}
    defaults: {_controller: AcmebsceneBundle:Meeting:addComment }
    
acmebscene_deleteComment:
    path: /meeting/deleteComment/{id}/{commentId}
    defaults:  {_controller: AcmebsceneBundle:Meeting:deleteComment }
   
    
acmebscene_verificationSent:
    path: /account/VerificationSent/{id}
    defaults: {_controller: AcmebsceneBundle:Account:sendVerification }
