acmebscene_eventComments:
    resource: "@AcmebsceneBundle/Resources/config/routing/eventcomments.yml"
    prefix:   /eventComments

acmebscene_speaker:
    resource: "@AcmebsceneBundle/Resources/config/routing/speaker.yml"
    prefix:   /speaker

acmebscene_meeting:
    resource: "@AcmebsceneBundle/Resources/config/routing/meeting.yml"
    prefix:   /meeting

acmebscene_organization:
    resource: "@AcmebsceneBundle/Resources/config/routing/organization.yml"
    prefix:   /organization

acmebscene_category:
    resource: "@AcmebsceneBundle/Resources/config/routing/categories.yml"
    prefix:   /category

acmebscene_account:
    resource: "@AcmebsceneBundle/Resources/config/routing/account.yml"
    prefix:   /account

acmebscene_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmebsceneBundle:Default:index }

acmebscene_dashboard:
    path:   /admin/{lastLogin}
    defaults: { _controller: AcmebsceneBundle:Admin:index }
 
acmebscene_adminComment:
    path:   /admin/comment/{lastLogin}
    defaults: { _controller: AcmebsceneBundle:Comment:adminIndex}

acmebscene_adminOrganization:
    path:   /admin/organization
    defaults: { _controller: AcmebsceneBundle:Organization:adminIndex}

meeting_admin_list:
    path:    /admin/newEvents/{lastLogin}
    defaults: { _controller: "AcmebsceneBundle:Admin:newMeetingList" }    
 
acmebscene_homepageCalender:
    path:     /calender
    defaults: { _controller: AcmebsceneBundle:Default:getEventsDayList }
    
acmebscene_eventDetail:
    path: /meeting/detail/{id}
    defaults: {_controller: AcmebsceneBundle:Meeting:show }
        
acmebscene_logout:
    path:   /logout
    defaults: { _controller: AcmebsceneBundle:Default:logout }
    
    
acmebscene_login:
    path:   ''
    defaults: { _controller: AcmebsceneBundle:Default:login }

acmebscene_keywordSearch:
    path: /meeting/searchResults/
    defaults: {_controller: AcmebsceneBundle:Meeting:keywordSearch }
    
acmebscene_categorySearch:
    path: /meeting/searchResults/{id}
    defaults: {_controller: AcmebsceneBundle:Meeting:categorySearch }
    
 
